// Generated by https://quicktype.io

import { Product } from "./product.model";

export interface CategoryCall {
    products: Product[];
    total:    number;
    skip:     number;
    limit:    number;
}

